insert into type(id, name, icon) values (101,'Filme', 'bi bi-camera-reels');
insert into type(id, name, icon) values (102,'Bücher', 'bi bi-book');
insert into type(id, name, icon) values (103,'Musik', 'bi bi-boombox');
insert into type(id, name, icon) values (104,'Artikel', 'bi bi-newspaper');

//insert into medium(id, name, type_id) values (1,'Beispiel Buch', 2);
//insert into medium(id, name, type_id) values (2,'Beispiel Film', 1);
//insert into medium(id, name, type_id) values (3,'Beispiel Musik', 3);
//insert into medium(id, name, type_id) values (4,'Beispiel Artikel', 4);

insert into medium(id, name, type_id, description, was_read, priority, author, image_link, link) values (105,'Faust', 102, 'Die Arbeit an seinem "Faust" hat Goethe von den Anfängen des Urfaust im Jahre 1772 bis zur Vollendung des 2. Teiles ein Jahr vor seinem Tode sein Leben lang beschäftigt.', false, 10, 'Johann Wolfgang von Goethe','https://images.thalia.media/00/-/ffe916c06cb24ff8a36dc85ad7491212/faust-i-hamburger-lesehefte.jpeg','https://www.thalia.de/shop/home/artikeldetails/A1000443876');
insert into medium(id, name, type_id, description, published_date, was_read, priority, image_link, link) values (106,'Interstellar', 101, 'Ein Forscherteam reist auf der Suche nach neuen Welten durch ein Wurmloch im Universum, um das Überleben der Menschheit sicherzustellen.', '2024-01-08', false, 5,'https://cdn.kinocheck.com/i/tz0ag6xk6y.jpg','https://www.imdb.com/title/tt0816692/');
insert into medium(id, name, type_id, description, published_date, was_read, priority, author, image_link, link) values (107,'The Now Now', 103, 'The Now Now is the sixth studio album recorded by the British virtual band Gorillaz', '2018-06-29', false, 4, 'Gorillaz', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fhmrock.com.br%2Fwp-content%2Fuploads%2F2018%2F06%2FUntitled-3.jpg&f=1&nofb=1&ipt=b3f254afa533a603def75740149c54b9ea9624c0a3a5e176614bd3ec9a888ff8&ipo=images','https://open.spotify.com/intl-de/album/1amYhlukNF8WdaQC3gKkgL?si=M7wz3cFVQaWXGUIQa66jDA');
insert into medium(id, name, type_id, description, published_date, was_read, priority, author, rating, image_link,link) values (108,'US-Demokraten im Kamala-Rausch', 104, 'Die Demokraten ordnen sich bedingungslos dem Ziel unter, Kamala Harris ins Weiße Haus zu tragen. Doch die internen Konflikte schwelen weiter. In welche Richtung werden sich Harris und ihre notorisch zerstrittene Partei bewegen?', '2024-08-24', true, 1, 'René Pfister', 5, 'https://cdn.prod.www.spiegel.de/images/85e279a9-0926-4b09-8c43-d60c7509257b_w960_r1.778_fpx50_fpy46.webp','https://www.spiegel.de/ausland/kamala-harris-im-wahlkampf-in-den-usa-eine-partei-im-kamala-rausch-a-03dcc149-a161-4589-94b4-b0ce7207ae65');
insert into medium(id, name, type_id, description, published_date, was_read, priority, rating, image_link, link) values (101,'1984', 103, 'London, 1984: Winston Smith, Geschichtsfälscher im Staatsdienst, verliebt sich in die schöne und geheimnisvolle Julia. Gemeinsam beginnen sie, die totalitäre Welt infrage zu stellen, als Teil derer sie bisher funktioniert haben. ', '2021-01-18', true, 5, 4, 'https://images.thalia.media/00/-/67845c875ae04636af33d92d9b129f6f/1984-gebundene-ausgabe-george-orwell.jpeg','https://www.thalia.de/shop/home/artikeldetails/A1059363477');
insert into medium(id, name, type_id, description, published_date, was_read, priority, author, rating,image_link, link) values (102,'Der Herr der Ringe - Die Gefährten', 101, 'Ein sanftmütiger Hobbit aus dem Auenland und seine acht Gefährten machen sich auf den Weg, um den mächtigen Einen Ring zu zerstören und so die Mittelerde vor dem dunklen Herrscher Sauron zu bewahren.', '2001-12-19', true, 8, 'Peter Jackson', 3,'https://de.web.img3.acsta.net/medias/nmedia/18/63/50/45/18693194.jpg','https://www.imdb.com/title/tt0120737/?ref_=fn_al_tt_1');
insert into medium(id, name, type_id, description, published_date, was_read, priority, author, rating, image_link, link) values (103,'Linken-Staatssekretär wechselt ins BSW-Lager', 104, 'Immer wieder wirbt das Bündnis Sahra Wagenknecht Politikerinnen und Politiker der Linken ab. Nun folgt mit Staatssekretär Friedrich Straetmanns ein Amtsträger. Er nennt mindestens zwei Gründe für seinen Wechsel.', '2024-08-26', true,5, 'Autor', 2,'https://cdn.prod.www.spiegel.de/images/6255e26e-3381-4892-a7dd-dc498d9ccf0e_w960_r1.778_fpx37_fpy54.webp','https://www.spiegel.de/politik/deutschland/friedrich-straetmanns-linken-staatssekretaer-wechselt-ins-bsw-lager-a-bef01466-257a-42cc-847f-5933440e2622');
insert into medium(id, name, type_id, description, published_date, was_read, priority, author, image_link, link) values (104,'The Slow Rush', 103, 'The Slow Rush is the fourth studio album by Australian musical project Tame Impala', '2020-02-14', false,5, 'Tame Impala', 'https://upload.wikimedia.org/wikipedia/en/5/54/Tame_Impala_-_The_Slow_Rush.png','https://open.spotify.com/intl-de/album/31qVWUdRrlb8thMvts0yYL?si=1BCdEnMbQ4a4WdlXIYE0tQ');




